{
    "swagger": "2.0",
    "schemes": [
        "http"
    ],
    "host": "localhost:3000",
    "info": {
        "version": "",
        "title": "minimal",
        "description": ""
    },
    "paths": {
        "/nodes/{node}/{variableslot}": {
            "parameters": [
                {
                    "name": "node",
                    "in": "path",
                    "required": true,
                    "type": "string"
                },
                {
                    "name": "variableslot",
                    "in": "path",
                    "required": true,
                    "type": "string"
                }
            ],
            "get": {
                "tags": [
                    "Nodes"
                ],
                "summary": "",
                "description": "",
                "operationId": "GET_nodes-node-variableslot",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "404": {
                        "description": "",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/nodes/{node}/{slot}": {
            "parameters": [
                {
                    "name": "node",
                    "in": "path",
                    "required": true,
                    "type": "string"
                },
                {
                    "name": "slot",
                    "in": "path",
                    "required": true,
                    "type": "string"
                }
            ],
            "post": {
                "tags": [
                    "Nodes"
                ],
                "summary": "",
                "description": "",
                "operationId": "POST_nodes-node-slot",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "",
                        "schema": {
                            "type": "null"
                        }
                    },
                    "404": {
                        "description": "",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/events/{node}": {
            "parameters": [
                {
                    "name": "node",
                    "in": "path",
                    "required": true,
                    "type": "string"
                }
            ],
            "get": {
                "tags": [
                    "Events"
                ],
                "summary": "",
                "description": "",
                "operationId": "GET_events-node",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "$ref": "#/parameters/trait:serverSentEventStream:todo"
                    }
                ],
                "responses": {
                    "200": {
                        "$ref": "#/responses/trait:serverSentEventStream:200"
                    },
                    "404": {
                        "description": "",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/events": {
            "parameters": [],
            "get": {
                "tags": [
                    "Events"
                ],
                "summary": "",
                "description": "",
                "operationId": "GET_events",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "$ref": "#/parameters/trait:serverSentEventStream:todo"
                    }
                ],
                "responses": {
                    "200": {
                        "$ref": "#/responses/trait:serverSentEventStream:200"
                    },
                    "default": {
                        "description": ""
                    }
                }
            }
        },
        "/nodes": {
            "parameters": [],
            "get": {
                "tags": [
                    "Nodes"
                ],
                "summary": "",
                "description": "",
                "operationId": "GET_nodes",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/nodeshort"
                            }
                        }
                    }
                }
            }
        },
        "/reset": {
            "parameters": [],
            "get": {
                "tags": [
                    "Reset"
                ],
                "summary": "",
                "description": "",
                "operationId": "GET_reset",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [],
                "responses": {
                    "204": {
                        "description": ""
                    }
                }
            }
        },
        "/nodes/{node}": {
            "parameters": [
                {
                    "name": "node",
                    "in": "path",
                    "required": true,
                    "type": "string"
                }
            ],
            "get": {
                "tags": [
                    "Nodes"
                ],
                "summary": "",
                "description": "",
                "operationId": "GET_nodes-node",
                "consumes": [],
                "produces": [
                    "application/json"
                ],
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "$ref": "#/definitions/nodedescription"
                        }
                    },
                    "404": {
                        "description": "",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "nodeshort": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "node": {
                        "type": "integer"
                    },
                    "name": {
                        "type": "string"
                    },
                    "protocolVersion": {
                        "type": "integer"
                    },
                    "aeslId": {
                        "type": "integer"
                    }
                },
                "required": [
                    "node",
                    "name",
                    "protocolVersion",
                    "aeslId"
                ]
            },
            "example": [
                {
                    "node": 1,
                    "name": "thymio-II",
                    "protocolVersion": 5,
                    "aeslId": 1
                },
                {
                    "node": 21,
                    "name": "thymio-II",
                    "protocolVersion": 5,
                    "aeslId": 2
                }
            ]
        },
        "nodedescription": {
            "type": "object",
            "examples": {
                "application/json": {
                    "node": 1,
                    "name": "thymio-II",
                    "protocolVersion": 5,
                    "aeslId": 1,
                    "bytecodeSize": 1534,
                    "variablesSize": 585,
                    "stackSize": 32,
                    "namedVariables": {
                        "_fwversion": 2,
                        "_id": 1,
                        "_productId": 1,
                        "acc": 3,
                        "button.backward": 1,
                        "button.center": 1,
                        "button.forward": 1,
                        "button.left": 1,
                        "button.right": 1,
                        "event.args": 32,
                        "event.source": 1,
                        "mic.intensity": 1,
                        "mic.threshold": 1,
                        "motor.left.pwm": 1,
                        "motor.left.speed": 1,
                        "motor.left.target": 1,
                        "motor.right.pwm": 1,
                        "motor.right.speed": 1,
                        "motor.right.target": 1,
                        "prox.comm.rx": 1,
                        "prox.comm.tx": 1,
                        "prox.ground.ambiant": 2,
                        "prox.ground.delta": 2,
                        "prox.ground.reflected": 2,
                        "prox.horizontal": 7,
                        "rc5.address": 1,
                        "rc5.command": 1,
                        "temperature": 1,
                        "timer.period": 2
                    },
                    "localEvents": {
                        "button.backward": "Backward button status changed",
                        "button.left": "Left button status changed",
                        "button.center": "Center button status changed",
                        "button.forward": "Forward button status changed",
                        "button.right": "Right button status changed",
                        "buttons": "Buttons values updated",
                        "prox": "Proximity values updated",
                        "prox.comm": "Data received on the proximity communication",
                        "tap": "A tap is detected",
                        "acc": "Accelerometer values updated",
                        "mic": "Fired when microphone intensity is above threshold",
                        "sound.finished": "Fired when the playback of a user initiated sound is finished",
                        "temperature": "Temperature value updated",
                        "rc5": "RC5 message received",
                        "motor": "Motor timer",
                        "timer0": "Timer 0",
                        "timer1": "Timer 1"
                    },
                    "constants": {},
                    "events": {}
                }
            },
            "properties": {
                "node": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "protocolVersion": {
                    "type": "integer"
                },
                "aeslId": {
                    "type": "integer"
                },
                "bytecodeSize": {
                    "type": "integer"
                },
                "variablesSize": {
                    "type": "integer"
                },
                "stackSize": {
                    "type": "integer"
                },
                "namedVariables": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "integer"
                        }
                    }
                },
                "localEvents": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        }
                    }
                },
                "constants": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "integer"
                        }
                    }
                },
                "events": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "integer"
                        }
                    }
                }
            },
            "required": [
                "node",
                "name",
                "protocolVersion",
                "aeslId",
                "bytecodeSize",
                "variablesSize",
                "stackSize",
                "namedVariables",
                "localEvents",
                "constants",
                "events"
            ],
            "example": {
                "node": 1,
                "name": "thymio-II",
                "protocolVersion": 5,
                "aeslId": 1,
                "bytecodeSize": 1534,
                "variablesSize": 585,
                "stackSize": 32,
                "namedVariables": {
                    "_fwversion": 2,
                    "_id": 1,
                    "_productId": 1,
                    "acc": 3,
                    "button.backward": 1,
                    "button.center": 1,
                    "button.forward": 1,
                    "button.left": 1,
                    "button.right": 1,
                    "event.args": 32,
                    "event.source": 1,
                    "mic.intensity": 1,
                    "mic.threshold": 1,
                    "motor.left.pwm": 1,
                    "motor.left.speed": 1,
                    "motor.left.target": 1,
                    "motor.right.pwm": 1,
                    "motor.right.speed": 1,
                    "motor.right.target": 1,
                    "prox.comm.rx": 1,
                    "prox.comm.tx": 1,
                    "prox.ground.ambiant": 2,
                    "prox.ground.delta": 2,
                    "prox.ground.reflected": 2,
                    "prox.horizontal": 7,
                    "rc5.address": 1,
                    "rc5.command": 1,
                    "temperature": 1,
                    "timer.period": 2
                },
                "localEvents": {
                    "button.backward": "Backward button status changed",
                    "button.left": "Left button status changed",
                    "button.center": "Center button status changed",
                    "button.forward": "Forward button status changed",
                    "button.right": "Right button status changed",
                    "buttons": "Buttons values updated",
                    "prox": "Proximity values updated",
                    "prox.comm": "Data received on the proximity communication",
                    "tap": "A tap is detected",
                    "acc": "Accelerometer values updated",
                    "mic": "Fired when microphone intensity is above threshold",
                    "sound.finished": "Fired when the playback of a user initiated sound is finished",
                    "temperature": "Temperature value updated",
                    "rc5": "RC5 message received",
                    "motor": "Motor timer",
                    "timer0": "Timer 0",
                    "timer1": "Timer 1"
                },
                "constants": {},
                "events": {}
            }
        }
    },
    "parameters": {
        "trait:serverSentEventStream:todo": {
            "name": "todo",
            "in": "query",
            "required": false,
            "type": "integer"
        }
    },
    "responses": {
        "trait:serverSentEventStream:200": {
            "description": "",
            "schema": {
                "type": "string"
            }
        }
    }
}
